//list of moodboards we can use for seeds the database
use resonant_spaces;
db.dropDatabase();

db.moodboards.insertMany([{
    name: "Pink Kitchen",
    savedArtworks: [
        {
            "copyright": null,
            "contextualtextcount": 0,
            "creditline": "Harvard Art Museums/Arthur M. Sackler Museum, From the Grilli Collection, Gift of Peter Grilli and Diana Grilli",
            "accesslevel": 1,
            "dateoflastpageview": "2023-06-23",
            "classificationid": 26,
            "division": "Asian and Mediterranean Art",
            "markscount": 0,
            "publicationcount": 0,
            "totaluniquepageviews": 220,
            "contact": "am_asianmediterranean@harvard.edu",
            "colorcount": 7,
            "rank": 125014,
            "id": 5244,
            "state": null,
            "verificationleveldescription": "Adequate. Object is adequately described but information may not be vetted",
            "period": "Edo period, 1615-1868",
            "images": "[{…}]",
            "worktypes": "[{…}, {…}]",
            "imagecount": 1,
            "totalpageviews": 259,
            "accessionyear": 2004,
            "standardreferencenumber": null,
            "signed": null,
            "classification": "Paintings",
            "relatedcount": 0,
            "verificationlevel": 2,
            "primaryimageurl": "https://nrs.harvard.edu/urn-3:HUAM:78905_dynmc",
            "titlescount": 2,
            "peoplecount": 0,
            "style": null,
            "lastupdate": "2023-07-15T05:33:42-0400",
            "commentary": null,
            "periodid": 248,
            "technique": null,
            "edition": null,
            "description": null,
            "medium": "Two-panel folding screen; ink, color and gold on silk",
            "lendingpermissionlevel": 0,
            "title": "Sixteen Arhats (Rakan) in a Fantastic Landscape",
            "accessionmethod": "Gift",
            "colors": "[{…}, {…}, {…}, {…}, {…}, {…}, {…}]",
            "provenance": null,
            "groupcount": 0,
            "dated": "Late Edo period, late 18th c. to 19th century",
            "department": "Department of Asian Art",
            "dateend": 1899,
            "url": "https://www.harvardartmuseums.org/collections/object/5244",
            "dateoffirstpageview": "2009-06-23",
            "century": "18th-19th century",
            "objectnumber": "2004.172",
            "labeltext": null,
            "datebegin": 1767,
            "culture": "Japanese",
            "exhibitioncount": 1,
            "imagepermissionlevel": 0,
            "mediacount": 0,
            "objectid": 5244,
            "techniqueid": null,
            "dimensions": "painting proper (combined dimensions of two panels): H. 174.9 x W. 174.1 cm (68 7/8 x 68 9/16 in.)",
            "seeAlso": "[{…}]"
    }
]
},
{
    name: "Green Bedroom",
    savedArtworks: [
        {
        "id": "18622751",
        "tms:id": "186212",
        "accession_number": "1987-57-3-a/c",
        "title": "Cup And Saucer (Spain)",
        "title_raw": null,
        "url": "https://collection.cooperhewitt.org/objects/18622751/",
        "has_no_known_copyright": null,
        "department_id": "35347497",
        "period_id": null,
        "media_id": "35389857",
        "type_id": "35248193",
        "date": "1986–87",
        "year_start": 1986,
        "year_end": 1987,
        "year_acquired": "1987",
        "decade": "1980",
        "woe:country_id": "23424950",
        "medium": "plastic",
        "markings": null,
        "signed": null,
        "inscribed": null,
        "provenance": null,
        "dimensions": "H x W x D (a): 7.3 x 12.5 x 10.5 cm (2 7/8 x 4 15/16 x 4 1/8 in.)\nH x diam. (b,c): 0.9 x 14 cm (3/8 x 5 1/2 in.)",
        "dimensions_raw": "{depth: Array(2), diameter: Array(2), height: Array…}",
        "creditline": "Gift of David R. McFadden",
        "description": null,
        "justification": null,
        "gallery_text": null,
        "label_text": null,
        "videos": null,
        "on_display": null,
        "woe:country": "23424950",
        "type": "cup and saucer",
        "images": "[{…}, {…}]",
        "participants": "[{…}]",
        "woe:country_name": "Spain",
        "is_loan_object": 0
    }
] 
}
])